# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Page.ui'
#
# Created by: Suraj Giri
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from Home_page import Ui_HomePage


class Ui_login_Page(object):
    def setupUi(self, login_Page):
        login_Page.setObjectName("login_Page")
        login_Page.resize(412, 463)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        login_Page.setFont(font)
        login_Page.setAutoFillBackground(True)
        login_Page.setDocumentMode(True)
        login_Page.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(login_Page)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(100, 220, 191, 41))
        self.login.setStyleSheet("background-image: url(\"\");\n"
"\n"
"font: 75 14pt \"Times New Roman\";\n"
"background-color:white; border:1px solid black; border-radius:20px; \n")
        self.login.setObjectName("login")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 120, 51, 20))
        self.label.setStyleSheet("font: 75 10pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 91, 20))
        self.label_2.setStyleSheet("font: 75 10pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.id = QtWidgets.QLineEdit(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(150, 120, 161, 20))
        self.id.setObjectName("id")
        self.pw = QtWidgets.QLineEdit(self.centralwidget)
        self.pw.setGeometry(QtCore.QRect(150, 170, 161, 20))
        self.pw.setText("")
        self.pw.setObjectName("pw")
        login_Page.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(login_Page)
        self.statusbar.setObjectName("statusbar")
        login_Page.setStatusBar(self.statusbar)
        self.login.clicked.connect(self.login1)
        self.retranslateUi(login_Page)
        QtCore.QMetaObject.connectSlotsByName(login_Page)

    def login1(self):
        try:
            id=self.id.text().lower()
            pw=self.pw.text().lower()   
            import mysql.connector
            cn=mysql.connector.connect(host="localhost",user="root",password="",database="trs")
            mycursor=cn.cursor()
            mycursor.execute("SELECT * FROM `trs_login` where trs_id like '"+id+"' and trs_pw like '"+pw+"' ")
            r=mycursor.fetchone()
            if r!=None:
                Message("Login","Login Success "+id)
                
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_HomePage()
                self.ui.setupUi(self.window)
                self.window.show()
                
            else:
                Message("Login","Login Failed")
        except:
                Message("Error","Error Occurred")
            
    def retranslateUi(self, login_Page):
        _translate = QtCore.QCoreApplication.translate
        login_Page.setWindowTitle(_translate("login_Page", "TRS - Login"))
        self.login.setText(_translate("login_Page", "Login"))
        self.label.setText(_translate("login_Page", "Enter ID:"))
        self.label_2.setText(_translate("login_Page", "Enter Password:"))


def Message(h,mssg):
        msg = QMessageBox()
        msg.setWindowTitle(h)
        msg.setText(mssg)
        msg.setIcon(QMessageBox.Information)
        msg.exec_()

   
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_Page = QtWidgets.QMainWindow()
    ui = Ui_login_Page()
    ui.setupUi(login_Page)
    login_Page.show()
    sys.exit(app.exec_())
    