# Generated by Django 4.1.1 on 2023-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_username', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('mobileno', models.BigIntegerField(blank=True, null=True)),
                ('customer_password', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'customer_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('customer_name', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=60)),
                ('customer_number', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('customer_message', models.CharField(max_length=100)),
                ('employee_reply', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer_query',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('customer_email', models.CharField(max_length=40)),
                ('customer_number', models.CharField(max_length=11)),
                ('room_booked', models.CharField(max_length=3)),
                ('no_of_people', models.CharField(max_length=3)),
                ('hotel_checkin', models.DateField()),
                ('hotel_checkout', models.IntegerField()),
                ('date_booked', models.IntegerField()),
            ],
            options={
                'db_table': 'hotel_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TourismPlan',
            fields=[
                ('plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=40, null=True)),
                ('plan_state', models.CharField(blank=True, max_length=30, null=True)),
                ('plan_details', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tourism_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TourRegistration',
            fields=[
                ('customer_name', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=60)),
                ('customer_phone', models.CharField(max_length=12)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_gender', models.CharField(max_length=8)),
                ('customer_country', models.CharField(max_length=20)),
                ('customer_state', models.CharField(max_length=20)),
                ('customer_passport', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_selected_package', models.CharField(max_length=16)),
                ('trip_startdate', models.DateField()),
                ('trip_enddate', models.DateField()),
                ('trip_amt', models.FloatField()),
                ('customer_payment', models.FloatField()),
                ('trip_status', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'tour_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsEmployee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_address', models.CharField(max_length=100)),
                ('emp_dob', models.DateField()),
                ('emp_mobno', models.BigIntegerField()),
                ('emp_sal', models.FloatField()),
                ('emp_saltax', models.FloatField()),
                ('emp_netsal', models.FloatField()),
                ('emp_type', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'trs_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsLogin',
            fields=[
                ('trs_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('trs_pw', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'trs_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('customer_name', models.CharField(max_length=50)),
                ('customer_license', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('customer_email', models.CharField(max_length=60)),
                ('customer_phone', models.CharField(max_length=11)),
                ('customer_pickup', models.DateField()),
                ('customer_drop', models.DateField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'vehicle_registration',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='trs_login',
        ),
    ]
