# Generated by Django 4.1.1 on 2023-07-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0002_customerdetails_customerquery_djangosession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'managed': True},
        ),
    ]
