# Generated by Django 4.1.1 on 2023-07-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0003_alter_customerdetails_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='customerquery',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tourismplan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tourregistration',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='trsemployee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='trslogin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vehicleregistration',
            options={'managed': True},
        ),
    ]
