# Generated by Django 4.1.1 on 2023-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0004_delete_djangosession_alter_customerquery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerquery',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tourismplan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tourregistration',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trsemployee',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trslogin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vehicleregistration',
            options={'managed': False},
        ),
    ]
